# Generated by Django 4.0.3 on 2022-03-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_books_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='catagory',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
