# Generated by Django 4.0.3 on 2022-03-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_remove_books_author_name_remove_books_book_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
    ]
