# Generated by Django 4.0.3 on 2022-03-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0005_books_rating_books_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='favourites',
            field=models.CharField(default='', max_length=200),
        ),
    ]
