# Generated by Django 4.0.3 on 2022-03-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0007_books_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='favourites',
            field=models.BooleanField(default=True),
        ),
    ]
