# Generated by Django 4.0.3 on 2022-03-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0008_alter_books_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(default='book.jpg', upload_to='books_pics'),
        ),
    ]
