# Generated by Django 4.0.3 on 2022-03-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0009_books_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='review',
            new_name='eview',
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Literary', 'Literary'), ('Mystery', 'Mystery'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('Fiction', 'Fiction'), ('Thriller', 'Thriller')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.IntegerField(max_length=5),
        ),
    ]
