# Generated by Django 4.0.3 on 2022-03-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0010_rename_review_books_eview_books_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
