# Generated by Django 4.0.3 on 2022-03-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0011_alter_books_image_alter_books_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='eview',
            new_name='review',
        ),
    ]
