# Generated by Django 4.0.3 on 2022-03-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0012_rename_eview_books_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
