# Generated by Django 4.0.3 on 2022-03-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0013_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Literary', 'Literary'), ('Mystery', 'Mystery'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('Fiction', 'Fiction'), ('Thriller', 'Thriller')], max_length=200, null=True),
        ),
    ]
