# Generated by Django 4.0.3 on 2022-03-07 18:51

from django.db import migrations, models
import ebook.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0014_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.IntegerField(validators=[ebook.models.validate_rate]),
        ),
    ]
