# Generated by Django 4.0.3 on 2022-03-07 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0015_alter_books_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='review',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(5)),
        ),
    ]
