# Generated by Django 4.0.3 on 2022-03-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0016_alter_books_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='review',
            field=models.IntegerField(),
        ),
    ]
