# Generated by Django 4.0.3 on 2022-03-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0017_alter_books_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='review',
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Literary', 'Literary'), ('Mystery', 'Mystery'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('Fiction', 'Fiction'), ('Thriller', 'Thriller')], default='null', max_length=200),
        ),
    ]
