# Generated by Django 4.0.3 on 2022-03-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0018_remove_books_review_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Literary', 'Literary'), ('Mystery', 'Mystery'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('Fiction', 'Fiction'), ('Thriller', 'Thriller')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], default='', max_length=200),
        ),
    ]
