# Generated by Django 4.0.3 on 2022-03-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0019_alter_books_category_alter_books_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='favourites',
            field=models.BooleanField(default=''),
        ),
    ]
